services:
  website:
    image: ghcr.io/palaguidebot/website:latest
    container_name: website
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - mongo_db

networks:
  mongo_db:
    external: true
