version: '3.3'

services:
  website:
    image: node:20.17.0
    container_name: website
    working_dir: /build
    volumes:
      - ./build:/build
      - ./node_modules:/build/node_modules
      - ./secrets:/build/secrets
    command: node bin/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge