/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#app/controllers/auth_controller'),
  Minecraft: () => import('#app/controllers/minecraft_controller'),
  Page: () => import('#app/controllers/page_controller'),
  event: {
    Event: () => import('#app/event/controllers/event_controller'),
    Giveaway: () => import('#app/event/controllers/giveaway_controller'),
  },
  leaderboard: {
    Alliance: () => import('#app/leaderboard/controllers/alliance_controller'),
    Boss: () => import('#app/leaderboard/controllers/boss_controller'),
    Chorus: () => import('#app/leaderboard/controllers/chorus_controller'),
    Clicker: () => import('#app/leaderboard/controllers/clicker_controller'),
    Egghunt: () => import('#app/leaderboard/controllers/egghunt_controller'),
    End: () => import('#app/leaderboard/controllers/end_controller'),
    Factions: () => import('#app/leaderboard/controllers/factions_controller'),
    Jobs: () => import('#app/leaderboard/controllers/jobs_controller'),
    Koth: () => import('#app/leaderboard/controllers/koth_controller'),
    Money: () => import('#app/leaderboard/controllers/money_controller'),
    Trixium: () => import('#app/leaderboard/controllers/trixium_controller'),
  },
  staff: {
    Dashboard: () => import('#app/staff/controllers/dashboard_controller'),
    Giveaway: () => import('#app/staff/controllers/giveaway_controller'),
    Role: () => import('#app/staff/controllers/role_controller'),
    User: () => import('#app/staff/controllers/user_controller'),
  },
  stats: {
    Faction: () => import('#app/stats/controllers/faction_controller'),
    Player: () => import('#app/stats/controllers/player_controller'),
  },
  status: {
    Paladium: () => import('#app/status/controllers/paladium_controller'),
  },
  tools: {
    controller: {
      Clicker: () => import('#app/tools/controller/clicker_controller'),
      JobCalculator: () => import('#app/tools/controller/job_calculator_controller'),
      PogCalculator: () => import('#app/tools/controller/pog_calculator_controller'),
    },
  },
}
